feat: add two phase
seata/seata-go pull request #43
Opened 2022-07-03 16:15 UTC by luky116

### Which issue(s) this PR fixes:

Fixes  https://github.com/seata/seata-go/issues/42

### Special notes for your reviewer:

### Does this PR introduce a user-facing change?:

2022-07-09 09:42 UTC, 106umao commented on pkg/rm/two_phase.go
> +	// prepared method has 2 params, context.Context, interface{}
这里注释有问题，对应代码，入参数量大于0就可以了。

2022-07-09 09:42 UTC, 106umao commented on pkg/rm/two_phase.go
> +	if outNum := t.Type.NumOut(); outNum != 2 {
commit和rollback方法不会没rpc comsumer调用，对照seata-java实现，不应该有interface{}入参，参数通过context传递。

2022-07-09 09:42 UTC, 106umao commented on pkg/rm/two_phase.go
> +	Commit(ctx context.Context, businessActionContext *tm.BusinessActionContext) (TwoPhaseResponse, error)
这里为什么需要两个context呢？是否可以只有一个businessActionContext？

2022-07-09 09:42 UTC, 106umao commented on pkg/rm/two_phase.go
> +	Rollback(ctx context.Context, businessActionContext *tm.BusinessActionContext) (TwoPhaseResponse, error)
commit和rollback的返回值固定为bool应该就可以了，tc只需要知道是否操作成功了。

2022-07-09 09:42 UTC, 106umao commented on pkg/rm/two_phase.go
> +	if returnType := t.Type.Out(0); returnType != typTwoPhaseResponse {
返回值是否可以确定为bool呢？

2022-07-09 09:42 UTC, 106umao commented on pkg/rm/two_phase.go
> +func getRollbackMethod(t reflect.StructField, f reflect.Value) (string, *reflect.Value, bool) {
同上getCommitMethod方法的问题。

2022-07-09 09:42 UTC, 106umao commented on pkg/rm/two_phase.go
> +	Prepare(ctx context.Context, params ...interface{}) (TwoPhaseResponse, error)
prepare的返回值应该用interface{}更合适

2022-07-11 00:28 UTC, luky116 commented on sample/tcc/dubbo/tt.go
> +package dubbo
这个文件不需要，删了

2022-07-11 00:30 UTC, luky116 commented on pkg/rm/two_phase.go
> +	if returnType := t.Type.Out(0); returnType != typTwoPhaseResponse {
嗯嗯，我想了下也是interface{}比较合适点

2022-07-11 00:34 UTC, luky116 commented on pkg/rm/two_phase.go
> +	// prepared method has 2 params, context.Context, interface{}
改为了“prepared method has at least 1 params, context.Context, and other params”，context是必须要的，里面传递了全局事务的状态

2022-07-11 01:09 UTC, luky116 commented on pkg/rm/two_phase.go
> +	Rollback(ctx context.Context, businessActionContext *tm.BusinessActionContext) (TwoPhaseResponse, error)
error还是需要的，error出了可以表示是否执行成功，还可以表示失败原因。还有一个原因，dubbo-go要求远程服务最后一个返回值必须是error，不然会报错

2022-07-11 01:09 UTC, luky116 commented on pkg/rm/two_phase.go
> +	Rollback(ctx context.Context, businessActionContext *tm.BusinessActionContext) (TwoPhaseResponse, error)
感觉这是go的习惯

2022-07-11 01:10 UTC, luky116 commented on pkg/rm/two_phase.go
> +	if returnType := t.Type.Out(0); returnType != typTwoPhaseResponse {
同上，感觉bool不太行

2022-07-11 01:13 UTC, luky116 commented on pkg/rm/two_phase.go
> +	Commit(ctx context.Context, businessActionContext *tm.BusinessActionContext) (TwoPhaseResponse, error)
context.Context参数是go的一个规范，所有函数第一个参数都可以加；但是BusinessActionContext是tcc事务的上下文，不能加在所有方法上

2022-07-11 01:13 UTC, luky116 commented on pkg/rm/two_phase.go
> +func getRollbackMethod(t reflect.StructField, f reflect.Value) (string, *reflect.Value, bool) {
getCommitMethod改了的，这个也一起改了

2022-07-11 01:13 UTC, luky116 commented on pkg/rm/two_phase.go
> +	if typeOf.Kind() != reflect.Struct {
是有点重复了，不过这个感觉还行哈

2022-07-11 01:17 UTC, luky116 commented on sample/tcc/dubbo/server/cmd/server.go
> +	err = userProviderProxy.RegisterResource()
理论上加这俩也能实现自动注册资源，但是也会增加用户理解的成本。如果想实现自动注册资源，感觉可以我们自己根据方法是否被dubbo代理来判断，这样能更方便，这也是一个思路。感觉可以再讨论下这个，后面确定方案了再修复也行

2022-07-11 01:21 UTC, 106umao commented on pkg/rm/two_phase.go
> +	Rollback(ctx context.Context, businessActionContext *tm.BusinessActionContext) (TwoPhaseResponse, error)
我的意思是说除了error以外可能只要一个bool就行了

2022-07-11 01:30 UTC, 106umao commented on pkg/rm/two_phase.go
> +	if typeOf.Kind() != reflect.Struct {
```suggestion

```

2022-07-11 01:31 UTC, 106umao commented on pkg/rm/two_phase.go
> +		return nil, errors.New("param should be a struct, instead of a pointer")
```suggestion

```

2022-07-11 01:31 UTC, 106umao commented on pkg/rm/two_phase.go
> +	}
```suggestion

```

2022-07-11 01:32 UTC, 106umao requested changes

2022-07-11 01:32 UTC, 106umao commented on pkg/rm/two_phase.go
> +		return nil, errors.New("invalid type kind")
```suggestion
		return nil, errors.New("param should be a struct, instead of a pointer")
```

2022-07-11 11:06 UTC, AlexStocks approved these changes

2022-07-12 02:59 UTC, closed without merging